import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

type Lang = 'es' | 'en';

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  es: {
    appTitle: 'PaySplit',
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    settings: 'Configuración',
    enter: 'Entrar',
    landingTitle: 'Bienvenido a PaySplit',
    landingSubtitle: 'Gestiona gastos compartidos de forma simple y eficiente.',
    start: 'Comenzar',
    footerRight: 'Hecho con Angular y Node.js',
    emailLabel: 'Email',
    passwordLabel: 'Contraseña',
    emailError: 'Por favor, introduce un email válido.',
    passwordError: 'La contraseña es obligatoria.',
    entering: 'Entrando...',
    noAccount: '¿No tienes cuenta? Regístrate',
    friends: 'Amigos',
    requests: 'Solicitudes',
    addFriend: 'Añadir amigo',
    friendRequestSent: 'Solicitud de amistad enviada',
    alreadyFriends: 'Ya eres amigo de este usuario',
    friendRequestExists: 'Ya has enviado una solicitud a este usuario',
    removeFriend: 'Eliminar amigo',
    back: 'Volver',
    cancel: 'Cancelar',
    save: 'Guardar',
    delete: 'Eliminar',
    edit: 'Editar',
    loading: 'Cargando...',
    saving: 'Guardando...',
    groups: 'Grupos',
    commonGroups: 'Grupos en común',
    members: 'Miembros',
    expenses: 'Gastos',
    balances: 'Balances',
    summary: 'Resumen',
    description: 'Descripción',
    amount: 'Monto',
    date: 'Fecha',
    paidBy: 'Pagado por',
    groupSettings: 'Configuración del grupo',
    groupProfile: 'Perfil del grupo',
    groupName: 'Nombre del grupo',
    saveChanges: 'Guardar cambios',
    changesSaved: 'Cambios guardados correctamente',
    errorSaving: 'No se pudieron guardar los cambios',
    registered: 'Registrado',
    noMembers: 'No hay miembros',
    noGroups: 'No tenéis grupos en común',
    welcome: 'Bienvenido a PaySplit',
    mustLoginFirst: 'Antes de continuar debes iniciar sesión o registrarte.',
    signup: 'Registrarse',
    signin: 'Iniciar sesión',
    name: 'Nombre',
    password: 'Contraseña',
    email: 'Email',
    signingUp: 'Registrando...',
    signingIn: 'Iniciando...',
    connectedAs: 'Conectado como',
    myGroups: 'Mis grupos',
    create: 'Crear',
    join: 'Unirse',
    newGroupName: 'Nombre del nuevo grupo',
    createGroup: 'Crear grupo',
    creating: 'Creando...',
    groupId: 'ID del grupo',
    joining: 'Uniendo...',
    loadingGroups: 'Cargando grupos...',
    currency: 'Moneda',
    sharedAccount: 'Cuenta compartida',
    addExpense: 'Añadir gasto',
    accountTotal: 'Total cuenta',
    yourTotal: 'Tu total pagado',
    noExpensesYet: 'No hay gastos todavía.',
    expenseHistory: 'Historial de gastos',
    by: 'por',
    editExpense: 'Editar gasto',
    deleteExpense: 'Eliminar gasto',
    divide: 'Dividir',
    add: 'Añadir',
    loadingBalances: 'Cargando balances...',
    paid: 'Pagó',
    share: 'Su parte',
    hidePassword: 'Ocultar contraseña',
    showPassword: 'Mostrar contraseña',
    landingBadge: 'Novedad: Gestión de grupos v2.0',
    landingHeading: 'Divide gastos,',
    landingHeadingGradient: 'multiplica experiencias.',
    landingDescription: 'La forma más sencilla de llevar las cuentas claras con amigos, compañeros de piso o en viajes. Sin hojas de cálculo, sin estrés.',
    startFree: 'Empezar Gratis',
    alreadyHaveAccount: 'Ya tengo cuenta',
    users: 'Usuarios',
    rating: 'Valoración',
    simplifySharedFinances: 'SIMPLIFICA TUS FINANZAS COMPARTIDAS',
    unlimitedGroups: 'Grupos Ilimitados',
    realTimeSync: 'Sincronización Real',
    clearBalances: 'Balances Claros',
    featureEqualSplit: 'División equitativa o personalizada',
    featureEqualSplitDesc: 'Divide los gastos por igual o asigna cantidades específicas a cada persona',
    featureTrackDebts: 'Seguimiento automático',
    featureTrackDebtsDesc: 'Sabe quién debe qué a quién en todo momento con balances actualizados',
    featureSettleUp: 'Liquidación simplificada',
    featureSettleUpDesc: 'Calcula la forma más eficiente de saldar todas las deudas del grupo',
    createAccount: 'Crear Cuenta',
    username: 'Nombre de Usuario',
    usernameError: 'El nombre debe tener al menos 3 caracteres.',
    passwordMinError: 'La contraseña debe tener al menos 6 caracteres.',
    alreadyHaveAccountLogin: '¿Ya tienes cuenta? Inicia sesión',
    youOwe: 'Debes',
    totalDebt: 'Deuda total',
    userSettings: 'Configuración de usuario',
    nombre: 'Nombre',
    theme: 'Tema',
    light: 'Claro',
    dark: 'Oscuro',
    deleteAccount: 'Eliminar cuenta',
  },
  en: {
    appTitle: 'PaySplit',
    login: 'Login',
    register: 'Register',
    settings: 'Settings',
    enter: 'Enter',
    landingTitle: 'Welcome to PaySplit',
    landingSubtitle: 'Manage shared expenses simply and efficiently.',
    start: 'Get Started',
    footerRight: 'Made with Angular and Node.js',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    emailError: 'Please enter a valid email.',
    passwordError: 'Password is required.',
    entering: 'Signing in...',
    noAccount: "Don't have an account? Register",
    friends: 'Friends',
    requests: 'Requests',
    addFriend: 'Add friend',
    friendRequestSent: 'Friend request sent',
    alreadyFriends: 'Already friends with this user',
    friendRequestExists: 'Friend request already sent to this user',
    removeFriend: 'Remove friend',
    back: 'Back',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    loading: 'Loading...',
    saving: 'Saving...',
    groups: 'Groups',
    commonGroups: 'Common groups',
    members: 'Members',
    expenses: 'Expenses',
    balances: 'Balances',
    summary: 'Summary',
    description: 'Description',
    amount: 'Amount',
    date: 'Date',
    paidBy: 'Paid by',
    groupSettings: 'Group settings',
    groupProfile: 'Group profile',
    groupName: 'Group name',
    saveChanges: 'Save changes',
    changesSaved: 'Changes saved successfully',
    errorSaving: 'Could not save changes',
    registered: 'Registered',
    noMembers: 'No members',
    noGroups: 'No groups in common',
    welcome: 'Welcome to PaySplit',
    mustLoginFirst: 'You must log in or register to continue.',
    signup: 'Sign up',
    signin: 'Sign in',
    name: 'Name',
    password: 'Password',
    email: 'Email',
    signingUp: 'Signing up...',
    signingIn: 'Signing in...',
    connectedAs: 'Connected as',
    myGroups: 'My groups',
    create: 'Create',
    join: 'Join',
    newGroupName: 'New group name',
    createGroup: 'Create group',
    creating: 'Creating...',
    groupId: 'Group ID',
    joining: 'Joining...',
    loadingGroups: 'Loading groups...',
    currency: 'Currency',
    sharedAccount: 'Shared account',
    addExpense: 'Add expense',
    accountTotal: 'Account total',
    yourTotal: 'Your total paid',
    noExpensesYet: 'No expenses yet.',
    expenseHistory: 'Expense history',
    by: 'by',
    editExpense: 'Edit expense',
    deleteExpense: 'Delete expense',
    divide: 'Divide',
    add: 'Add',
    loadingBalances: 'Loading balances...',
    paid: 'Paid',
    share: 'Share',
    hidePassword: 'Hide password',
    showPassword: 'Show password',
    landingBadge: 'New: Group management v2.0',
    landingHeading: 'Split expenses,',
    landingHeadingGradient: 'multiply experiences.',
    landingDescription: 'The easiest way to keep track with friends, roommates or on trips. No spreadsheets, no stress.',
    startFree: 'Start Free',
    alreadyHaveAccount: 'I already have an account',
    users: 'Users',
    rating: 'Rating',
    simplifySharedFinances: 'SIMPLIFY YOUR SHARED FINANCES',
    unlimitedGroups: 'Unlimited Groups',
    realTimeSync: 'Real-Time Sync',
    clearBalances: 'Clear Balances',
    featureEqualSplit: 'Equal or custom split',
    featureEqualSplitDesc: 'Split expenses equally or assign specific amounts to each person',
    featureTrackDebts: 'Automatic tracking',
    featureTrackDebtsDesc: 'Know who owes what to whom at all times with updated balances',
    featureSettleUp: 'Simplified settlement',
    featureSettleUpDesc: 'Calculate the most efficient way to settle all group debts',
    createAccount: 'Create Account',
    username: 'Username',
    usernameError: 'Name must be at least 3 characters.',
    passwordMinError: 'Password must be at least 6 characters.',
    alreadyHaveAccountLogin: 'Already have an account? Sign in',
    youOwe: 'You owe',
    totalDebt: 'Total debt',
    userSettings: 'User Settings',
    nombre: 'Name',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    deleteAccount: 'Delete Account',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private lang$ = new BehaviorSubject<Lang>('es');

  get current() {
    return this.lang$.value;
  }

  get changes() {
    return this.lang$.asObservable();
  }

  toggle() {
    const next: Lang = this.current === 'es' ? 'en' : 'es';
    this.lang$.next(next);
  }

  t(key: string) {
    return TRANSLATIONS[this.current][key] ?? key;
  }
}
