import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

type Lang = 'es' | 'en';

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  es: {
    appTitle: 'PaySplit',
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    settings: 'Configuración',
    enter: 'Entrar',
    landingTitle: 'Bienvenido a PaySplit',
    landingSubtitle: 'Gestiona gastos compartidos de forma simple y eficiente.',
    start: 'Comenzar',
    footerRight: 'Hecho con Angular y Node.js',
    footerTagline:
      'Simplifica la gestión de gastos en grupo. Transparencia y equidad para todos.',
    footerBrand: 'Grupo 18',
    emailLabel: 'Email',
    passwordLabel: 'Contraseña',
    emailError: 'Por favor, introduce un email válido.',
    passwordError: 'La contraseña es obligatoria.',
    entering: 'Entrando...',
    noAccount: '¿No tienes cuenta? Regístrate',
    friends: 'Amigos',
    requests: 'Solicitudes',
    notifications: 'Notificaciones',
    groupInvitations: 'Invitaciones',
    noRequests: 'No hay solicitudes',
    addFriend: 'Añadir amigo',
    friendRequestSent: 'Solicitud de amistad enviada',
    alreadyFriends: 'Ya eres amigo de este usuario',
    friendRequestExists: 'Ya has enviado una solicitud a este usuario',
    removeFriend: 'Eliminar amigo',
    back: 'Volver',
    cancel: 'Cancelar',
    save: 'Guardar',
    delete: 'Eliminar',
    edit: 'Editar',
    loading: 'Cargando...',
    saving: 'Guardando...',
    groups: 'Grupos',
    commonGroups: 'Grupos en común',
    members: 'Miembros',
    expenses: 'Gastos',
    balances: 'Balances',
    summary: 'Resumen',
    description: 'Descripción',
    amount: 'Monto',
    date: 'Fecha',
    paidBy: 'Pagado por',
    groupSettings: 'Configuración del grupo',
    groupProfile: 'Perfil del grupo',
    groupName: 'Nombre del grupo',
    saveChanges: 'Guardar cambios',
    changesSaved: 'Cambios guardados correctamente',
    errorSaving: 'No se pudieron guardar los cambios',
    registered: 'Registrado',
    noMembers: 'No hay miembros',
    noGroups: 'No tenéis grupos en común',
    welcome: 'Bienvenido a PaySplit',
    mustLoginFirst: 'Antes de continuar debes iniciar sesión o registrarte.',
    signup: 'Registrarse',
    signin: 'Iniciar sesión',
    name: 'Nombre',
    password: 'Contraseña',
    email: 'Email',
    signingUp: 'Registrando...',
    signingIn: 'Iniciando...',
    connectedAs: 'Conectado como',
    myGroups: 'Mis grupos',
    create: 'Crear',
    join: 'Unirse',
    newGroupName: 'Nombre del nuevo grupo',
    createGroup: 'Crear grupo',
    creating: 'Creando...',
    groupId: 'ID del grupo',
    joining: 'Uniendo...',
    loadingGroups: 'Cargando grupos...',
    currency: 'Moneda',
    sharedAccount: 'Cuenta compartida',
    addExpense: 'Añadir gasto',
    accountTotal: 'Total pagado',
    yourTotal: 'Tu total pagado',
    noExpensesYet: 'No hay gastos todavía.',
    expenseHistory: 'Historial de gastos',
    by: 'por',
    editExpense: 'Editar gasto',
    deleteExpense: 'Eliminar gasto',
    deleteGroup: 'Eliminar grupo',
    divide: 'Dividir automáticamente',
    add: 'Añadir',
    loadingBalances: 'Cargando balances...',
    paid: 'Pagó',
    share: 'Su parte',
    hidePassword: 'Ocultar contraseña',
    showPassword: 'Mostrar contraseña',
    landingBadge: 'Novedad: Gestión de grupos v2.0',
    landingHeading: 'Divide gastos,',
    landingHeadingGradient: 'multiplica experiencias.',
    landingDescription:
      'La forma más sencilla de llevar las cuentas claras con amigos, compañeros de piso o en viajes. Sin hojas de cálculo, sin estrés.',
    startFree: 'Empezar Gratis',
    alreadyHaveAccount: 'Ya tengo cuenta',
    users: 'Usuarios',
    rating: 'Valoración',
    simplifySharedFinances: 'SIMPLIFICA TUS FINANZAS COMPARTIDAS',
    unlimitedGroups: 'Grupos Ilimitados',
    realTimeSync: 'Sincronización Real',
    clearBalances: 'Balances Claros',
    featureEqualSplit: 'División equitativa o personalizada',
    featureEqualSplitDesc:
      'Divide los gastos por igual o asigna cantidades específicas a cada persona',
    featureTrackDebts: 'Seguimiento automático',
    featureTrackDebtsDesc:
      'Sabe quién debe qué a quién en todo momento con balances actualizados',
    featureSettleUp: 'Liquidación simplificada',
    featureSettleUpDesc:
      'Calcula la forma más eficiente de saldar todas las deudas del grupo',
    createAccount: 'Crear Cuenta',
    username: 'Nombre de Usuario',
    usernameError: 'El nombre debe tener al menos 3 caracteres.',
    passwordMinError: 'La contraseña debe tener al menos 6 caracteres.',
    alreadyHaveAccountLogin: '¿Ya tienes cuenta? Inicia sesión',
    youOwe: 'Debes',
    youAreOwed: 'Te deben',
    youWillReceive: 'Recibirás',
    youHavePaid: 'Has pagado',
    netBalance: 'Balance neto',
    youOweNet: 'Debes en este grupo',
    youAreOwedNet: 'Te deben en este grupo',
    balanced: 'Equilibrado',
    totalDebt: 'Deuda total',
    userSettings: 'Configuración de usuario',
    nombre: 'Nombre',
    theme: 'Tema',
    light: 'Claro',
    dark: 'Oscuro',
    logout: 'Salir',
    deleteAccount: 'Eliminar cuenta',
    dailyExpenses: 'Gastos diarios',
    addMember: 'Añadir miembro',
    totalExpenses: 'Total de gastos',
    yourBalance: 'Tu balance',
    quickActions: 'Acciones rápidas',
    stats: 'Estadísticas',
    group: 'Grupo',
    createFirstExpense: 'Crear primer gasto',
    pay: 'Pagar',
    reject: 'Rechazar',
    responded: 'Respondida',
    paymentRequest: 'Solicitud de pago',
    paymentConfirmed: 'Pago confirmado',
    newExpense: 'Nuevo gasto',
    groupInvitation: 'Invitación a grupo',
    friendRequest: 'Solicitud de amistad',
    notification: 'Notificación',
    paymentRequestMessage: 'Te solicitan el pago de',
    paymentConfirmedMessage: 'Pago de',
    confirmed: 'confirmado',
    newExpenseMessage: 'Se ha creado un nuevo gasto en el grupo',
    groupInvitationMessage: 'Te han invitado a unirte a un grupo',
    friendRequestMessage: 'Te ha enviado una solicitud de amistad',
    sending: 'Enviando',
    requestSent: 'Solicitud enviada',
    close: 'Cerrar',
    accept: 'Aceptar',
    backButton: 'Volver',
    refreshButton: 'Actualizar',
    detailsExpense: 'Detalles del Gasto',
    participants: 'Participantes',
    helloUser: 'Hola',
    quickActionsLabel: 'Acciones Rápidas',
    createGroupLabel: 'Crear Grupo',
    joinGroupLabel: 'Unirse a Grupo',
    statsLabel: 'Estadísticas del Grupo',
    totalBalance: 'Balance Total',
    youOweLabel: 'Debes',
    youAreOwedLabel: 'Te deben',
    invalidLink: 'Enlace de invitación inválido',
    linkExpired: 'Este enlace de invitación ha expirado',
    linkMaxUses: 'Este enlace ha alcanzado el número máximo de usos',
    invalidLinkMessage: 'El enlace de invitación no es válido',
    userNotFound: 'Usuario no identificado.',
    groupNotFound: 'Grupo no encontrado',
    failedLoadGroups: 'No se pudieron cargar los grupos',
    failedLoadExpenses: 'No se pudieron cargar los gastos',
    failedDeleteExpense: 'No se pudo eliminar el gasto: ',
    failedDeleteGroup: 'No se pudo eliminar el grupo',
    failedSaveSettings: 'Error al guardar cambios',
    failedDeleteAccount: 'No se pudo eliminar la cuenta: ',
    failedCopyId: 'No se pudo copiar el ID',
    linkCreatedCopied: 'Enlace creado y copiado al portapapeles: ',
    linkCopied: 'Enlace copiado al portapapeles',
    failedRevokeLink: 'Error al revocar el enlace',
    friendRemoved: 'Amigo eliminado',
    nowText: 'Ahora',
    paymentSuccess: 'Solicitud de pago enviada',
    friendRequestSuccess: '¡Ahora eres amigo de',
    noFriendRequests: 'No tienes solicitudes pendientes',
    noFriendsList: 'No tienes amigos',
    ago: 'Hace',
    user: 'Usuario',
    totalGroups: 'Total de grupos:',
    activeGroups: 'Grupos activos:',
    all: 'Todos',
    active: 'Activos',
    recentlyUpdated: 'Actualizado recientemente',
    noDescription: 'Sin descripción',
    noActiveGroups: 'No tienes grupos activos',
    createFirstGroupHelp:
      'Crea tu primer grupo o únete a uno existente para comenzar',
    guestTitle: 'Controla tus gastos compartidos',
    guestSubtitle:
      'La forma más fácil de dividir cuentas con amigos y familia.',
    enterGroupName: 'Introduce un nombre para el grupo.',
    failedCreateGroup: 'No se pudo crear el grupo',
    enterGroupId: 'Introduce el id del grupo.',
    failedJoinGroup: 'No se pudo unir al grupo',
    searchUser: 'Buscar usuario',
    typeUserName: 'Escribe el nombre...',
    noResults: 'No se encontraron usuarios',
    youAreFriends: 'Ya son amigos',
    friendRequestSentMsg: 'Solicitud de amistad enviada',
    sendInvitation: 'Enviar solicitud',
    removeFriendConfirm: '¿Eliminar amigo',
    friendDeletedMsg: 'Amigo eliminado',
    errorDelete: 'Error: ',
    errorAccept: 'No se pudo aceptar la solicitud',
    errorReject: 'No se pudo rechazar la solicitud',
    rejectConfirm: '¿Rechazar solicitud de',
    errorSearch: 'Error al buscar usuarios',
    errorInvalidUser: 'Error: Usuario no seleccionado',
    errorInvalidId: 'Error: ID de usuario inválido',
    errorUserNotExists: 'El usuario no existe en el sistema',
    errorSendRequest: 'No se pudo enviar la solicitud',
    errorUserNotFound: 'El usuario no existe o no se puede acceder a su perfil',
    friendRequestSentTo: 'Solicitud de amistad enviada a',
    youHaveSent: 'Te ha enviado una solicitud de amistad',
    maxUses: 'Usos máximos',
    expirationDays: 'Días hasta expirar',
    unlimited: 'Ilimitado',
    noExpiration: 'Sin expiración',
    invitationLinks: 'Enlaces de invitación',
    createLink: 'Crear enlace',
    noActiveLinks: 'No hay enlaces activos',
  },
  en: {
    appTitle: 'PaySplit',
    login: 'Login',
    register: 'Register',
    settings: 'Settings',
    enter: 'Enter',
    landingTitle: 'Welcome to PaySplit',
    landingSubtitle: 'Manage shared expenses simply and efficiently.',
    start: 'Get Started',
    footerRight: 'Made with Angular and Node.js',
    footerTagline:
      'Simplify group expense management. Transparency and fairness for everyone.',
    footerBrand: 'Grupo 18',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    emailError: 'Please enter a valid email.',
    passwordError: 'Password is required.',
    entering: 'Signing in...',
    noAccount: "Don't have an account? Register",
    friends: 'Friends',
    requests: 'Requests',
    notifications: 'Notifications',
    groupInvitations: 'Invites',
    noRequests: 'No requests',
    addFriend: 'Add friend',
    friendRequestSent: 'Friend request sent',
    alreadyFriends: 'Already friends with this user',
    friendRequestExists: 'Friend request already sent to this user',
    removeFriend: 'Remove friend',
    back: 'Back',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    loading: 'Loading...',
    saving: 'Saving...',
    groups: 'Groups',
    commonGroups: 'Common groups',
    members: 'Members',
    expenses: 'Expenses',
    balances: 'Balances',
    summary: 'Summary',
    description: 'Description',
    amount: 'Amount',
    date: 'Date',
    paidBy: 'Paid by',
    groupSettings: 'Group settings',
    groupProfile: 'Group profile',
    groupName: 'Group name',
    saveChanges: 'Save changes',
    changesSaved: 'Changes saved successfully',
    errorSaving: 'Could not save changes',
    registered: 'Registered',
    noMembers: 'No members',
    noGroups: 'No groups in common',
    welcome: 'Welcome to PaySplit',
    mustLoginFirst: 'You must log in or register to continue.',
    signup: 'Sign up',
    signin: 'Sign in',
    name: 'Name',
    password: 'Password',
    email: 'Email',
    signingUp: 'Signing up...',
    signingIn: 'Signing in...',
    connectedAs: 'Connected as',
    myGroups: 'My groups',
    create: 'Create',
    join: 'Join',
    newGroupName: 'New group name',
    createGroup: 'Create group',
    creating: 'Creating...',
    groupId: 'Group ID',
    joining: 'Joining...',
    loadingGroups: 'Loading groups...',
    currency: 'Currency',
    sharedAccount: 'Shared account',
    addExpense: 'Add expense',
    accountTotal: 'Total paid',
    yourTotal: 'Your total paid',
    noExpensesYet: 'No expenses yet.',
    expenseHistory: 'Expense history',
    by: 'by',
    editExpense: 'Edit expense',
    deleteExpense: 'Delete expense',
    deleteGroup: 'Delete group',
    divide: 'Divide automatically',
    add: 'Add',
    loadingBalances: 'Loading balances...',
    paid: 'Paid',
    share: 'Share',
    hidePassword: 'Hide password',
    showPassword: 'Show password',
    landingBadge: 'New: Group management v2.0',
    landingHeading: 'Split expenses,',
    landingHeadingGradient: 'multiply experiences.',
    landingDescription:
      'The easiest way to keep track with friends, roommates or on trips. No spreadsheets, no stress.',
    startFree: 'Start Free',
    alreadyHaveAccount: 'I already have an account',
    users: 'Users',
    rating: 'Rating',
    simplifySharedFinances: 'SIMPLIFY YOUR SHARED FINANCES',
    unlimitedGroups: 'Unlimited Groups',
    realTimeSync: 'Real-Time Sync',
    clearBalances: 'Clear Balances',
    featureEqualSplit: 'Equal or custom split',
    featureEqualSplitDesc:
      'Split expenses equally or assign specific amounts to each person',
    featureTrackDebts: 'Automatic tracking',
    featureTrackDebtsDesc:
      'Know who owes what to whom at all times with updated balances',
    featureSettleUp: 'Simplified settlement',
    featureSettleUpDesc:
      'Calculate the most efficient way to settle all group debts',
    createAccount: 'Create Account',
    username: 'Username',
    usernameError: 'Name must be at least 3 characters.',
    passwordMinError: 'Password must be at least 6 characters.',
    alreadyHaveAccountLogin: 'Already have an account? Sign in',
    youOwe: 'You owe',
    youAreOwed: 'You are owed',
    youWillReceive: 'You will receive',
    youHavePaid: 'You have paid',
    netBalance: 'Net Balance',
    youOweNet: 'You owe in this group',
    youAreOwedNet: 'You are owed in this group',
    balanced: 'Balanced',
    totalDebt: 'Total debt',
    userSettings: 'User Settings',
    nombre: 'Name',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    logout: 'Logout',
    deleteAccount: 'Delete Account',
    dailyExpenses: 'Daily Expenses',
    addMember: 'Add member',
    totalExpenses: 'Total expenses',
    yourBalance: 'Your balance',
    quickActions: 'Quick actions',
    stats: 'Stats',
    group: 'Group',
    createFirstExpense: 'Create first expense',
    pay: 'Pay',
    reject: 'Reject',
    responded: 'Responded',
    paymentRequest: 'Payment Request',
    paymentConfirmed: 'Payment Confirmed',
    newExpense: 'New Expense',
    groupInvitation: 'Group Invitation',
    friendRequest: 'Friend Request',
    notification: 'Notification',
    paymentRequestMessage: 'You are requested to pay',
    paymentConfirmedMessage: 'Payment of',
    confirmed: 'confirmed',
    newExpenseMessage: 'A new expense has been created in the group',
    groupInvitationMessage: 'You have been invited to join a group',
    friendRequestMessage: 'has sent you a friend request',
    sending: 'Sending',
    requestSent: 'Request Sent',
    close: 'Close',
    accept: 'Accept',
    backButton: 'Back',
    refreshButton: 'Refresh',
    detailsExpense: 'Expense Details',
    participants: 'Participants',
    helloUser: 'Hello',
    quickActionsLabel: 'Quick Actions',
    createGroupLabel: 'Create Group',
    joinGroupLabel: 'Join Group',
    statsLabel: 'Group Statistics',
    totalBalance: 'Total Balance',
    youOweLabel: 'You Owe',
    youAreOwedLabel: 'You Are Owed',
    invalidLink: 'Invalid invitation link',
    linkExpired: 'This invitation link has expired',
    linkMaxUses: 'This link has reached the maximum number of uses',
    invalidLinkMessage: 'The invitation link is not valid',
    userNotFound: 'User not identified.',
    groupNotFound: 'Group not found',
    failedLoadGroups: 'Could not load groups',
    failedLoadExpenses: 'Could not load expenses',
    failedDeleteExpense: 'Failed to delete expense: ',
    failedDeleteGroup: 'Failed to delete group',
    failedSaveSettings: 'Failed to save settings',
    failedDeleteAccount: 'Failed to delete account: ',
    failedCopyId: 'Failed to copy ID',
    linkCreatedCopied: 'Link created and copied to clipboard: ',
    linkCopied: 'Link copied to clipboard',
    failedRevokeLink: 'Failed to revoke link',
    friendRemoved: 'Friend removed',
    nowText: 'Now',
    paymentSuccess: 'Payment request sent',
    friendRequestSuccess: 'Now you are friends with',
    noFriendRequests: 'You have no pending requests',
    noFriendsList: 'You have no friends',
    ago: 'Ago',
    user: 'User',
    totalGroups: 'Total groups:',
    activeGroups: 'Active groups:',
    all: 'All',
    active: 'Active',
    recentlyUpdated: 'Recently updated',
    noDescription: 'No description',
    noActiveGroups: 'You have no active groups',
    createFirstGroupHelp:
      'Create your first group or join an existing one to start',
    guestTitle: 'Control your shared expenses',
    guestSubtitle: 'The easiest way to split bills with friends and family.',
    enterGroupName: 'Enter a name for the group.',
    failedCreateGroup: 'Could not create group',
    enterGroupId: 'Enter the group id.',
    failedJoinGroup: 'Could not join the group',
    searchUser: 'Search user',
    typeUserName: 'Type name...',
    noResults: 'No users found',
    youAreFriends: 'Already friends',
    friendRequestSentMsg: 'Friend request sent',
    sendInvitation: 'Send request',
    removeFriendConfirm: 'Remove friend',
    friendDeletedMsg: 'Friend removed',
    errorDelete: 'Error: ',
    errorAccept: 'Could not accept request',
    errorReject: 'Could not reject request',
    rejectConfirm: 'Reject request from',
    errorSearch: 'Error searching users',
    errorInvalidUser: 'Error: User not selected',
    errorInvalidId: 'Error: Invalid user ID',
    errorUserNotExists: 'User does not exist',
    errorSendRequest: 'Could not send request',
    errorUserNotFound: 'User does not exist or cannot access profile',
    friendRequestSentTo: 'Friend request sent to',
    youHaveSent: 'has sent you a friend request',
    maxUses: 'Max Uses',
    expirationDays: 'Expiration Days',
    unlimited: 'Unlimited',
    noExpiration: 'No Expiration',
    invitationLinks: 'Invitation Links',
    createLink: 'Create Link',
    noActiveLinks: 'No active links',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private lang$ = new BehaviorSubject<Lang>('es');

  get current() {
    return this.lang$.value;
  }

  get changes() {
    return this.lang$.asObservable();
  }

  toggle() {
    const next: Lang = this.current === 'es' ? 'en' : 'es';
    this.lang$.next(next);
  }

  t(key: string) {
    return TRANSLATIONS[this.current][key] ?? key;
  }
}
